### ISSUE TITLE
Its showing everything was updated a few seconds ago but hasnt been touched for days/weeks

### ISSUE THREAD

**Issue by nick-gray** [SomeoneWeird/cirrus#7]
![image](https://cloud.githubusercontent.com/assets/13723883/14371113/87ab4e0e-fd77-11e5-9317-4de8bb5229a9.png)

**Comment by SomeoneWeird** [comment]
Indeed, I noticed that last night too. Not sure what caused that, I can look later.

**Comment by SomeoneWeird** [comment]
Fixed in 0b8bbba9463ce9a91a9fa94d55ff8a5234614b0a
